UPDATE car
SET transmission = CASE
    WHEN transmission IS NULL OR TRIM(transmission) = '' THEN 'AUTOMATIC'
    WHEN UPPER(TRIM(transmission)) IN ('AUTOMATIC', 'AUTO', 'AT') THEN 'AUTOMATIC'
    WHEN UPPER(TRIM(transmission)) IN ('MANUAL', 'MT') THEN 'MANUAL'
    ELSE 'AUTOMATIC'
END;

UPDATE car
SET fuel_type = CASE
    WHEN fuel_type IS NULL OR TRIM(fuel_type) = '' THEN 'GASOLINE'
    WHEN UPPER(TRIM(fuel_type)) IN ('GASOLINE', 'GAS', 'PETROL') THEN 'GASOLINE'
    WHEN UPPER(TRIM(fuel_type)) = 'DIESEL' THEN 'DIESEL'
    WHEN UPPER(TRIM(fuel_type)) IN ('ELECTRIC', 'EV') THEN 'ELECTRIC'
    WHEN UPPER(TRIM(fuel_type)) = 'HYBRID' THEN 'HYBRID'
    ELSE 'GASOLINE'
END;

ALTER TABLE car
    MODIFY COLUMN transmission ENUM('AUTOMATIC','MANUAL') NOT NULL DEFAULT 'AUTOMATIC',
    MODIFY COLUMN fuel_type ENUM('GASOLINE','DIESEL','ELECTRIC','HYBRID') NOT NULL DEFAULT 'GASOLINE';
