package vehicle.booking.entity.enums;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_DEPOSIT_PAID,
    BOOKING_CONFIRMED,
    BOOKING_RENTING,
    BOOKING_RETURNED,
    BOOKING_DUE_TODAY,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    CAR_LOCATION_UPDATED,
    SYSTEM
}
